In [1]:
import numpy as np

In [2]:
ncells = 16
ql_binary = np.zeros(16)
indices = np.array([2,3,5,8,12,14,15])
for c, value in enumerate(ql_binary):
    if c in indices:
        ql_binary[c] = 1

print ql_binary

[0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1.]


In [3]:
neighbours = np.zeros((16,3),'int')
neighbours[0,:] = 1,-1,-1
neighbours[1,:] = 2,14,0
neighbours[2,:] = 3,1,-1
neighbours[3,:] = 4,12,2
neighbours[4,:] = 5,3,-1
neighbours[5,:] = 6,10,4
neighbours[6,:] = 7,5,-1
neighbours[7,:] =-1,8,6
neighbours[8,:] = -1,9,7
neighbours[9,:] = 8,-1,10
neighbours[10,:] = 9,11,5
neighbours[11,:] = 10,-1,12
neighbours[12,:] = 11,13,3
neighbours[13,:] = 12,-1,14
neighbours[14,:] = 13,15,1
neighbours[15,:] = 14,-1,-1

neighbours


array([[ 1, -1, -1],
       [ 2, 14,  0],
       [ 3,  1, -1],
       [ 4, 12,  2],
       [ 5,  3, -1],
       [ 6, 10,  4],
       [ 7,  5, -1],
       [-1,  8,  6],
       [-1,  9,  7],
       [ 8, -1, 10],
       [ 9, 11,  5],
       [10, -1, 12],
       [11, 13,  3],
       [12, -1, 14],
       [13, 15,  1],
       [14, -1, -1]])

In [4]:
import os
path = '/home/thirza/Cusize_python/PyRipser/python'
os.chdir(path)

from unionfind import UnionFind

In [5]:
ql_binary[0]

0.0

In [7]:
# Old one:

test = UnionFind(ncells)

for j in range(0, ncells-1):
    if ql_binary[j]:
        for i in range(0,2):
            cell_index = neighbours[j,i]
            if cell_index != -1:
                if ql_binary[cell_index]:
                    print neighbours[j,i]
                    test.link(j,neighbours[j,i])
                    
print test.parent

3
12
15
[ 0  1  3  3  4  5  6  7  8  9 10 11  3 13 15 15]


In [6]:
idx_clouds = np.array(np.where(ql_binary))[0]



In [7]:
nr_cloud_cells = len(idx_clouds)

print idx_clouds

test = UnionFind(nr_cloud_cells)

#for j in idx_clouds[0]:
for j in range(0,nr_cloud_cells):
    cell_1 = idx_clouds[j]
    for i in range(0,3):
        cell_2 = neighbours[cell_1,i]
        if cell_2 != -1:
            if ql_binary[cell_2]:
                idx_2 = np.where(idx_clouds==cell_2)
                test.link(j,idx_2)


for j in range(0, nr_cloud_cells):
    test.find(j)
        
print test.parent

[ 2  3  5  8 12 14 15]
[1 1 2 3 1 6 6]


In [8]:
cloud_label = 0
cloud_size_long = np.zeros(ncells)

parents = set(test.parent)
print parents
for p in parents:
    #print '%d --- %s' % (p, np.where(test.parent == p))
    idx_parent = np.where(test.parent == p)
    print idx_parent
    cloud_cells = idx_clouds[idx_parent]
    print cloud_cells
    cloud_size_long[cloud_label] = len(idx_parent[0])
    cloud_label += 1
    
    
cloud_size = np.trim_zeros(cloud_size_long)
print cloud_size
nr_clouds = len(cloud_size)
print nr_clouds

set([1, 2, 3, 6])
(array([0, 1, 4]),)
[ 2  3 12]
(array([2]),)
[5]
(array([3]),)
[8]
(array([5, 6]),)
[14 15]
[3. 1. 1. 2.]
4


In [7]:
test2 = UnionFind(10)

test2.link(3,4)
test2.link(4,5)
        
print test2.parent
print test2.rank

parents = test2.parent

for j in range(0,10):
    print test2.find(j)
    

[0 1 2 4 4 4 6 7 8 9]
[0 0 0 0 1 0 0 0 0 0]
0
1
2
4
4
4
6
7
8
9


In [8]:
unique, counts = np.unique(parents, return_counts=True)

print unique
print counts

[0 1 2 4 6 7 8 9]
[1 1 1 3 1 1 1 1]
